plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "scripts/validate_10.rb"

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
